### ISSUE TITLE
Not clear where the kubectl binary is being downloaded to.

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/zalando-kubectl#14]
On the very first run you will see this message:

```
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.4.6/bin/linux/amd64/kubectl.. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . OK
```

It's not clear where the binary is getting downloaded to, I think it should be clear to the users.

Also, in case you already have a `kubectl` binary in your path this step might be unnecessary.

**Comment by hjacobs** [comment]
Yes, we also need to make the download location configurable as it's currently "by job" on CI/CD (but we want to use one common download location).
