### ISSUE TITLE
zkubectl logs doesn't work when omitting container name

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando-incubator/zalando-kubectl#20]
If i try to execute:

` zkubectl logs <pod-name> --previous`

i am getting an error back: `Error from server (BadRequest): the server rejected our request for an unknown reason (get pods <pod-name>)`

it should at least behave like `kubectl`:

`Error from server: a container name must be specified for pod <pod-name>, choose one of: [<list-of-containers>]`

**Comment by Raffo** [comment]
This error is not related to `zalando-kubectl`, but to `kubectl` version `1.5.1`. I can replicate it consistently when the container name is not specified.

**Comment by Raffo** [comment]
@ChristianLohmann just to be sure, can you paste the output of: 

`zkubectl version`

`kubectl version`

Thanks!

**Comment by ChristianLohmann** [comment]
ok, with `kubectl` `v1.4.3` it works. That's the version i have currently installed

**Comment by hjacobs** [comment]
kubectl 1.5.3 (#29) fixes some annoying error messages like "the server rejected our request for an unknown reason" --- it now becomes "container sdf is not valid for pod "
