### ISSUE TITLE
Configuration files are stored in "wrong" place, under macOS

### ISSUE THREAD

**Issue by akauppi** [zalando-incubator/zalando-kubectl#34]
`zalando-kubectl` has its configuration files under `~/Library/Application\ Support/zalando-kubectl/`, on macOS.

The `Application Support` folders are intended for configuration files of GUI applications, not command line tools, in macOS. So this is not the recommended place for storing such files.

Using `/usr/local/etc/zalando-kubectl` feels like the right place, to me.

Obviously, this does not matter functionally - both work. It's just a convention. I tried to search for the root document stating that, but maybe it's somewhere deep in Apple SDK's, don't know.

It would simply look more professional, if we had these under `/usr/local/etc`:

```
fullstop
kio
mai
pierone
piu
senza
stups
zalando-aws-cli
zalando-deploy-cli
zalando-kubectl
zalando-token-cli
zign
```

Suggestion:

To minimize hazzle, new command line tools such as `zalando-kubectl` could start observing the convention while leaving "old" tools alone. This way we would avoid breaking documentations and tutorials that can be all over the place.

**Comment by hjacobs** [comment]
@akauppi AFAIK our CLI library uses this package to get the right folder: https://pypi.python.org/pypi/appdirs

We should not come up with another (our own) spec/definition...

**Comment by hjacobs** [comment]
`/usr/local/etc` is not a good place as it might not be writable by the user (it's a system directory, not user specific).

**Comment by akauppi** [comment]
On machines that I can imaging using `zkubectl` on Macs, the person is likely a developer and will have write access to `/usr/local/etc`. Anyways, since it's a third-party module deciding the location and since I didn't find reference to an Apple doc describing the use of different folders, I'm happy to close the issue.
